apiVersion: v1
kind: Service
metadata:
  name: callprocessor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80          # what the Ingress / other pods use
      targetPort: http  # the container's 8080
